### PR TITLE
Add gradient transformer

### PR DESCRIPTION
**Pull request by dougwperez**
This PR adds a basic gradient transformer, as well as tests to verify.

### CODE REVIEW

**Comment by lukasoppermann** [comment]
Hey, this is great.
I'd love to add gradient support. However since there is a [w3c spec for gradients](https://design-tokens.github.io/community-group/format/#gradient) I'd love to use it for the transformer as well.

```js
{
  "mostly-yellow": {
    "$type": "gradient",
    "$value": [
      {
        "color": "#ffff00",
        "position": 0.666
      },
      {
        "color": "#ff0000",
        "position": 1
      }
    ]
  }
}
```

The specs don't include an angle. However until they do add an angle we can add an optional angle property:

```js
{
  "mostly-yellow": {
    "$type": "gradient",
    "angle": 45,
    "$value": [
      {
        "color": "#ffff00",
        "position": 0.666
      },
      {
        "color": "#ff0000",
        "position": 1
      }
    ]
  }
}
```

Would you be able to adjust this PR?

**Comment by dougwperez** [comment]
> Hey, this is great. I'd love to add gradient support. However since there is a [w3c spec for gradients](https://design-tokens.github.io/community-group/format/#gradient) I'd love to use it for the transformer as well.
> 
> ```js
> {
>   "mostly-yellow": {
>     "$type": "gradient",
>     "$value": [
>       {
>         "color": "#ffff00",
>         "position": 0.666
>       },
>       {
>         "color": "#ff0000",
>         "position": 1
>       }
>     ]
>   }
> }
> ```
> 
> The specs don't include an angle. However until they do add an angle we can add an optional angle property:
> 
> ```js
> {
>   "mostly-yellow": {
>     "$type": "gradient",
>     "angle": 45,
>     "$value": [
>       {
>         "color": "#ffff00",
>         "position": 0.666
>       },
>       {
>         "color": "#ff0000",
>         "position": 1
>       }
>     ]
>   }
> }
> ```
> 
> Would you be able to adjust this PR to be more inline with the specs?

Yeah no problem! Let me implement this.

**Comment by dougwperez** [comment]
Hey @lukasoppermann , are there any other w3c transformers (aside from gradients) that you need help with?

**Comment by dougwperez** [comment]
Hey @lukasoppermann hope all is well on your end! I updated the PR to include your suggestions. Let me know if you have any suggestions. Thanks!

**Comment by lukasoppermann** [comment]
Hey, looks great. I have two things:

1. Why did you add json5 and this packages to the package.json? Can we remove that?
2. Could you add a second test with an angle. It would be great to have both tests. And maybe add a third test with more items in the gradient.

And did you run the test? Somehow I have the feeling this code does not work. I think in the transformer it would need to iterate over the array items from `$value`, doesn't it?

**Comment by dougwperez** [comment]
@lukasoppermann I implemented the suggestions you made in the previous comment. Just one question, concerning the gradient transformer, it seems we are returning an array within an array. Not quite sure how to address this but open to suggestions.

**Comment by lukasoppermann** [comment]
@dougwperez great, I will have a look.

Concerning the array, do you mean hear: https://github.com/lukasoppermann/style-dictionary-utils/pull/15/files#diff-befdab94e5d95c5d68b731e690edf7505c5d88476571b20485be8221fc518c0bR14 ?

We could just use `join(",")` right? Or are you talking about something else?

**Comment by dougwperez** [comment]
@lukasoppermann, I just pushed up some changes (prior to your edits to the comment). Take a look, and I can use your code in the comment if necessary.

**Comment by lukasoppermann** [comment]
Hey, I can't see the changes, are you sure you pushed it? 

Otherwise sounds good, we can continue on Wednesday. 👍

**Comment by dougwperez** [comment]
@lukasoppermann  Just pushed up now. 👍

**Comment by lukasoppermann** [comment]
Hey @dougwperez the changes are good. But what I mentioned above is still needed.

**Comment by dougwperez** [comment]
@lukasoppermann Hi, I implemented your suggested code. Just had to use the trim() method to remove some whitespaces and add a ternary condition for adding the "%" and the "," only when an angle or a position argument are provided. Let me know if this works.

**Comment by lukasoppermann** [comment]
Hey @dougwperez I have a few nitpicky changes. Would you rather I comment on them or are you fine with me merging and changing it afterwards? What do you feel better about>

**Comment by lukasoppermann** [comment]
Just a bit of cleanup like 

```js
${Math.floor(stop.position * 100) || ""}${stop.position ? "%" : ""}
// to
${stop.position ? `${Math.floor(stop.position * 100)}%` : ""}
```

**Comment by lukasoppermann** [comment]
It's shipped, thanks for the help.

**Pull request merged**
